version: '3.7'

networks:
  nginx_net:
    external: true

services:
  drone-server:
    image: drone/drone:latest
    container_name: drone
    ports:
      - 10081:80
    volumes:
      - ./data/drone:/var/lib/drone/
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - nginx_net
    env_file:
      # 环境变量都放到一个文件里面
      - ./config/server.env
  drone-runner:
    image: drone/drone-runner-docker:latest
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - nginx_net
    env_file:
      - ./config/runner.env